### ISSUE TITLE
Interest in new features in text editor?

### ISSUE THREAD

**Issue by jncraton** [ringgaard/sanos#1]
Thanks for building the Sanos text editor!

I really like the design principles behind the Sanos text editor, and I'm considering using it as a jumping off point for creating an editor designed to meet my needs. In particular, I love the idea of sticking with the principle of least surprise, but I'd like to add some features that make the Sanos editor a bit easier to integrate into my development process, which is basically the [Unix as an IDE paradigm](https://sanctum.geek.nz/arabesque/unix-as-ide-introduction/).

In particular, I'm considering implementing the following:

- Command line argument processing for internal commands. 
    - `edit -l 20 edit.c` would open the editor with the cursor on line 20 of edit.c. This makes it quicker to jump to compiler errors. 
    - `edit -f find_text edit.c` would open the editor and jump to the first occurrence of the string "find_text" in the file edit.c.
-  Consider the current line to be the current selection when nothing is selected.
    - This makes it a bit quicker to copy/cut/paste single lines, which is a common operation. I don't envision this causing much confusion given that the operations have no meaning when used without a selection currently.
- Ctrl+D to duplicate the current selection. This is very simple, and I've submitted a PR for this one.
- Remove Crtl+G as find_next. Modify Ctrl+F to find_next if there is text currently selected. Basically, Ctrl+F becomes find the next occurrence of the current selection or find as it is currently if nothing is selected.
- Bind Ctrl+G as goto line in addition to Ctrl+L (this matches Sublime and some other editors)
- Implement search in project/directory and basic search by symbol (i.e. [Sublime's Goto Anything](http://docs.sublimetext.info/en/latest/file_management/file_navigation.html#goto-anything)). This is a relatively large feature and for such a lean editor might actually double the size of the code base.

I see that there haven't been any commits to this project in years, but I wanted to check to see if you'd be interested in having any of the above merged at some point or if you have suggestions for changes that you would want merged. There's no hard feelings either way. I completely understand if you just want to keep this as lean as possible.

**Comment by ringgaard** [comment]
Hi Jon,

Thanks for your interest in the Sanos editor.

I made the editor many years ago as part of a small operating system I had
made. I wanted to have a simple text editor, but all the ones I could find
were too complicated and had too many dependencies on other libraries, so I
ended up writing my own editor. I am not really doing much development on
the editor anymore, mostly just fixing bugs and adding minor features.

I haven't really done anything to build a community around the editor, and
today I think its primary purpose is to serve as an example of how to
implement a basic gap buffer with replace/insert/erase/undo/redo
functionality. There are plenty of powerful editors around, so the small
niche that the Sanos editor fills is as a simple starting point for making
your own editor if you don't want to write one from scratch. There are all
sorts of things you could add to make it more useful, but I think that
keeping it simple is what makes it unique compared to most other editors.

You are welcome to branch/copy the code and use it as a starting point for
your own editor with the features that you like. I think this will be much
more productive for you than having me trying to build consensus around
what features will be useful.

Regards,
Michael

**Comment by jncraton** [comment]
Sounds good. Thanks for your insights! I won't worry about upstreaming any features back to you.

I'll send PRs for any bugs that I happen to find and fix if it is reasonable for me to do so.
