### ISSUE TITLE
edit not working over serial line on Linux.

### ISSUE THREAD

**Issue by mcondarelli** [ringgaard/sanos#6]
Hi,
thanks for the good work.

I am unsure if this is the right place to report bugs in "edit", I found nothing better; please redirect me as needed.

I found a small (but show-stopping) error in the Linux implementation:
```c
  struct termios tio;
  struct termios orig_tio;
  ...
  tcgetattr(0, &orig_tio);
  cfmakeraw(&tio);  
  tcsetattr(0, TCSANOW, &tio);
```
should be:
```c
  struct termios tio;
  struct termios orig_tio;
  ...
  tcgetattr(0, &orig_tio);
  tio = orig_tio;                   // <-- this line is missing
  cfmakeraw(&tio);  
  tcsetattr(0, TCSANOW, &tio);
```
otherwise `struct termios tio` is not correctly initialized and bad things happen, especially so if the underlying terminal is a serial line.

**Comment by ringgaard** [comment]
Thanks for reporting this bug. I have fixed this [here](https://github.com/ringgaard/sanos/commit/b6ea5cb56f9f6b76c7664865067ac812a7efdc96) and deployed a new version.
